apiVersion: v1
kind: Service
metadata:
  name: classifier
  namespace: contourguessr
  labels:
    app: classifier
spec:
  type: ClusterIP
  selector:
    app: classifier
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: classifier
  namespace: contourguessr
  labels:
    app: classifier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: classifier
  template:
    metadata:
      labels:
        app: classifier
    spec:
      containers:
        - name: classifier
          image: "ghcr.io/dzfranklin/cg-classifier:v0.1"
          ports:
            - containerPort: 80
              name: http
